language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*@dev

before_script:
  - wget https://getcomposer.org/composer.phar
  - php composer.phar require symfony/symfony:${SYMFONY_VERSION} --no-update
  - php composer.phar install --dev --prefer-source
  - sudo pip install -r Resources/doc/requirements.txt

script: make test

notifications:
    webhooks: http://sonata-project.org/bundles/page/master/travis

matrix:
  allow_failures:
    - php: hhvm
