<?php
/*
 * This file is part of the Sonata project.
 *
 * (c) Thomas Rabaix <thomas.rabaix@sonata-project.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Sonata\PageBundle\Site;

use Symfony\Component\Routing\RequestContext;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\HttpKernel\Event\GetResponseEvent;

use Sonata\PageBundle\Model\SiteManagerInterface;
use Sonata\PageBundle\Model\SiteInterface;
use Sonata\PageBundle\CmsManager\DecoratorStrategyInterface;

abstract class BaseSiteSelector implements SiteSelectorInterface
{
    protected $siteManager;

    protected $decoratorStrategy;

    protected $site;

    protected $request;

    /**
     * @param \Sonata\PageBundle\Model\SiteManagerInterface $siteManager
     * @param \Sonata\PageBundle\CmsManager\DecoratorStrategyInterface $decoratorStrategy
     */
    public function __construct(SiteManagerInterface $siteManager, DecoratorStrategyInterface $decoratorStrategy)
    {
        $this->siteManager = $siteManager;
        $this->decoratorStrategy = $decoratorStrategy;
    }

    /**
     * @return \Sonata\PageBundle\Model\SiteInterface
     */
    public function retrieve()
    {
        return $this->site;
    }

    /**
     * @param \Sonata\PageBundle\Model\SiteInterface $site
     * @return void
     */
    public function set(SiteInterface $site)
    {
        if (!$this->request) {
            return;
        }

        $this->request->getSession()->set('sonata/page/site/current', $site->getId());
    }

    protected function setRequest($request)
    {
        $this->request = $request;
    }

    /**
     * @return array
     */
    protected function getSites()
    {
        if (!$this->request) {
            throw new \RuntimeException('No Request attached');
        }

        $siteId = $this->request->getSession() ? $this->request->getSession()->get('sonata/page/site/current') : false;

        $sites = array();
        if ($siteId) {
            $site = $this->siteManager->findOneBy(array('id' => $siteId));

            if ($site) {
                $sites = array($site);
            }
        }

        if (count($sites) == 0) {
            $sites = $this->siteManager->findBy(array(
                'host'    => array($this->request->getHost(), 'localhost'),
                'enabled' => true,
            ));
        }

        return $sites;
    }

    /**
     * This method hijack the path generated by the Generator cache file to use
     * the relative path from the current active site.
     *
     * @param \Symfony\Component\HttpKernel\Event\GetResponseEvent $event
     * @return void
     */
    public function onKernelRequestRedirect(GetResponseEvent $event)
    {

    }

    final public function onKernelRequest(GetResponseEvent $event)
    {
        if (!$this->decoratorStrategy->isRouteUriDecorable($event->getRequest()->getPathInfo())) {
            return;
        }

        $this->setRequest($event->getRequest());

        $this->handleKernelRequest($event);
    }

    /**
     * @abstract
     * @param \Symfony\Component\HttpKernel\Event\GetResponseEvent $event
     * @return void
     */
    abstract protected function handleKernelRequest(GetResponseEvent $event);

    /**
     * @return \Symfony\Component\Routing\RequestContext
     */
    public function getRequestContext()
    {
        return new RequestContext();
    }
}