<?php

declare(strict_types=1);

/*
 * This file is part of the Sonata Project package.
 *
 * (c) Thomas Rabaix <thomas.rabaix@sonata-project.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Sonata\PageBundle\Site;

use Sonata\PageBundle\Model\SiteInterface;
use Symfony\Component\HttpKernel\Event\RequestEvent;
use Symfony\Component\Routing\RequestContext;

/**
 * SiteSelectorInterface.
 *
 * @author Thomas Rabaix <thomas.rabaix@sonata-project.org>
 */
interface SiteSelectorInterface
{
    /**
     * @return SiteInterface|null
     */
    public function retrieve();

    /**
     * @return RequestContext
     */
    public function getRequestContext();

    public function onKernelRequest(RequestEvent $event);

    /**
     * This method hijack the path generated by the Generator cache file to use
     * the relative path from the current active site.
     */
    public function onKernelRequestRedirect(RequestEvent $event);
}
